export const CHANGE_TYPE = "CHANGE_TYPE";
export const CHANGE_URL_IMAGE = "CHANGE_URL_IMAGE"; 
export const CHANGE_SIZE = "CHANGE_SIZE"; 
export const CHANGE_GENDER = "CHANGE_GENDER"; 
export const CHANGE_CATEGORY = "CHANGE_CATEGORY"; 
export const CHANGE_LOCALIZATION = "CHANGE_LOCALIZATION"; 
export const CHANGE_DESCRIPTION = "CHANGE_DESCRIPTION"; 
export const CREATE_PET = "CREATE_PET"; 